- name: install debian prerequisites
  apt:  name={{ item }} state=present
  with_items:
    - libsasl2-dev 
    - libldap2-dev 
    - libssl-dev
    - python
    - python-pip
    - python-dev 
    - git
    - build-essential
    - gcc
